export const GET_URHEILIJATIEDOT = "GET_URHEILIJATIEDOT";
export const GET_URHEILIJA = "GET_URHEILIJATIETO";
export const DELETE_URHEILIJA = "DELETE_URHEILIJATIETO";
export const ADD_URHEILIJA = "ADD_URHEILIJATIETO";
export const EDIT_URHEILIJA = "EDIT_URHEILIJATIETO";
